### ISSUE TITLE
Simple React App Example

### ISSUE THREAD

**Issue by magbicaleman** [framer/framer-bridge-starter-kit#16]
I'm trying to wrap my head around how to use `framer-bridge-starter-kit` with a simple react app. Mainly around the concept of what repo should own the production coded components. 

Some questions:
- Where do I add my react application? 
  - Does it get created in the root of my forked `framer-bridge-starter-kit`, so that I can import the `design-system` components to be used in my app?
  - Does it get created as a sibling directory; meaning both `my-react-app` dir, and `framer-bridge-starter-kit` sit at the same level. 
    - Where do my actual components live, in the `my-react-app` and get system linked to the `framer-bridge-starter-kit`, or do I just import in my react app by `../framer-bridge-starter-kit/design-system/components`
- When this has been forked and I created a new component in the `framer-bridge-starter-kit/design-system/components/` directory, do I need to use the framer CLI to `build` so that my *.framerfx has new the component available to it? I'm not sure if I missed how that part works in the README. I'm aware they need to be exported in the index.ts, but what makes them available for me to use inside of framer once a new one has been added.

**Comment by magbicaleman** [comment]
To answer my own question and to whomever else might be wondering, especially if you're coming from `https://github.com/shiftsave/framerx-build-system` you don't need to worry about it "building".

When you edit code in the `design-system` directory it reflects changes in FramerX without you needing to close it and reopen the file. This is probably hugely possible because of the .framerfx file being a folder project instead of binary. 

> When this has been forked and I created a new component in the framer-bridge-starter-kit/design-system/components/ directory, do I need to use the framer CLI to build so that my *.framerfx has new the component available to it? I'm not sure if I missed how that part works in the README. I'm aware they need to be exported in the index.ts, but what makes them available for me to use inside of framer once a new one has been added.

**Comment by addisonschultz** [comment]
I think the main thing here is that the components consumed in Framer X are only references to the actual components in your React App, so the file would sit outside the Application itself, yet in the same directory so you can point back to them.

There are definitely other ways to set this up, especially if you're interested in keeping the .framerfx file outside the whole application itself, but this would require them to be built and hosted somewhere else, like NPM. 

Check out this article for some ideas on how to set up your components in Framer X, or shoot me a message if you want to chat a bit more! 

https://medium.com/@addisonschultz/design-systems-in-framer-x-e013c065457c
