### ISSUE TITLE
type errors in canvas.tsx

### ISSUE THREAD

**Issue by mikkmartin** [framer/framer-bridge-starter-kit#25]
importing components into a different environment eg. react storybook with typescript throws errors:
`import { Button } from '../design-system/components/Button'`

`TS2724: Module '"../../../../../../../Users/user/Library/Application Support/Framer X/Library/build/framer"' has no exported member 'createDesignComponent'. Did you mean 'createMotionComponent'?`

adding a `//@ts-ignore` for the import temporarily fixes the problem, but since the file gets autogenerated and re-written by framerX then this gets over-written.

**Comment by addisonschultz** [comment]
Can you explain the workflow you're aiming for with this setup? This tells me you're trying to use elements created on the canvas in a production env, which isn't going to work (`createDesignComponent`)

**Comment by mikkmartin** [comment]
Ok, i'll try and explain a bit more.

I was thinking how to develop a design system for a project. The plan was to setup a dev environment where it's easy to develop and test production components. Aka adding storybook to the repo. So UI engineers can run storybook to develop production components to publish and use in other projects. And also be wrapped and used in the included Framer project to export as a framer package.

So once I added storybook and started importing components from `/design-system` the storybook ts resolver gave the typescript error. So I looked into it and saw that aha! the design system production components import the colors in the `theme.tsx` from the `design-system.framerfx/code/canvas.tsx` that gives the type error shown above (not really using `createDesignComponent`  but the ts resolver throws).

Maybe my approach is not intended/ideal. I'm open for other suggestions on how to develop the actual production components by engineers who don't know/want to know about framer.

**Comment by addisonschultz** [comment]
I see your use case, but the error does make sense and is expected given Framer's canvas exports won't work in production. I'll try and make this a bit more clear! I think overall though, the workflow might look a little different then, as you'd most likely want to define your theme alongside your production design system, and not pull it from Framer

**Comment by addisonschultz** [comment]
Thanks for the feedback though. I'll go through this and see what we can do to make this a bit more flexible. Closing the ticket for now, but if you have any other questions feel free to re-open or ping me directly!

**Comment by mikkmartin** [comment]
If i'm importing the colors from the production – not vice versa: how do you keep them in sync and use them in the framer package?

**Comment by addisonschultz** [comment]
You could use it two ways! If your components are already explicitly set to accept your theme/colors (on the production side), you wont have to do anything. 

If you want to use your colors as [shared colors ](https://www.framer.com/blog/posts/introducing-shared-colors/), you could use a utility [like this one](https://github.com/tisho/framer-shared-colors-cli) to import them and keep them in sync :)

**Comment by mikkmartin** [comment]
While a good option, but:
1. Have to run this manually every time colors update in the repo (to be fair its not too often they change)
2. There is no clear notification indicating they have changed (and i have to import them again to get the latest colors)

Would much more prefer framer being the single source of truth. (Where they get tested and created – being design tool and all) and then imported to production from shared colors (and this being automatic). There might be 

Maybe a weird usecase, but thought it might be something to consider

**Comment by addisonschultz** [comment]
Yeah that totally does make sense. I think though in most setups, teams want to have the production version as their source of truth vs the version in their design tool. That being said, to help with point #1, you would most likely have some sort of CI/CD workflow setup (I would recommend CircleCI) to run scripts every time something is changed.

Example: Devs change some styles and colors in the master repo, and push this to production. Here you could set up a CircleCI workflow that imports these new colors into your framer project. That's sort of the idea with Framer Bridge in the first place, that your production components _**live**_ outside of Framer, but you can use / test / iterate on them within the tool

**Comment by mikkmartin** [comment]
Thanks, will probably go for something like that. Just curious – why does the starter kit import them from framer canvas in the first place? What's the workflow intended here? How do you propose the production level components get created? Let's say I want to add some new component:
I fire up framer + my code editor of choice. Create the pure "production" component in the editor. Then import that in the framer "code component" and start iterating on the component inside framer using the preview?

**Comment by addisonschultz** [comment]
I think it's imported this way to show an example that this is possible. The starter kit is more of a way to illustrate how 1 way a design system could be integrated with Framer, although there are many other ways to approach a unified setup like this.

The workflow you mention is exactly the way I would go about this. You can use Framer in a similar way like [Storybook](https://storybook.js.org/), where you build your components in production, but test them visually in Framer. The added benefit of using Framer is that you can design interfaces, test components in a larger environment, and continue building on them using things like overrides.
