### ISSUE TITLE
framer-cli publish does not recognize already published package's name

### ISSUE THREAD

**Issue by kmiyashiro** [framer/framer-bridge-starter-kit#26]
I have a previously published package in our private store. Running `framer version` correctly identifies the name and currently published version of the package in our store. However, running `framer publish` attempts to publish the package under a new name and 1.0.0 version.

I expect that the framer-cli would publish a new version of the same package, not publish it as a new package.

```
➜  demo.framerfx git:(master) framer version
🗂  Latest version of @framer/j4edvhm9.demo-components is v1.57.0.
➜  demo.framerfx git:(master) ✗ framer publish
Ready to publish @framer/intercom.demo-components v1.0.0 (private store). Continue (y/N)? 
```

<img width="640" alt="Screen Shot 2020-06-09 at 12 27 54 PM" src="https://user-images.githubusercontent.com/71852/84191946-23062e00-aa4e-11ea-99bf-aef603dab744.png">

**Comment by addisonschultz** [comment]
It looks like the name of the framer project (in `package.json`) was updated to something new, is it possible to share the project at all? You can also DM me [here](https://discord.com/channels/341919693348536320/707195309285179424/720190206308909096)

**Comment by addisonschultz** [comment]
This issue was resolved with a recent update to the Framer CLI.
