### ISSUE TITLE
"Cannot reject pending version" error on publish

### ISSUE THREAD

**Issue by harrywincup** [framer/framer-bridge-starter-kit#27]
Hey everyone,

I'm hoping somebody can tell me what this slightly mysterious error means please? I've tried various combinations of `npx framer-cli publish ...` flags but I'm not sure if it's telling me I already have it published and I need to do something?

Thanks in advance!

**Comment by addisonschultz** [comment]
Do you have more details on the error messaging you're getting?

The last command you ran + the error that is returned would be helpful!

**Comment by harrywincup** [comment]
@addisonschultz Apologies, I should've been clearer. 

1. I run the following command (team id redacted here)
```npx framer-cli publish ./cosmos.framerfx --team="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" --new="Cosmos"```

2. It asks if I'm ready to publish to my private store for the team. I choose `y`.

3. The output is this error, which I googled but didn't find any info for.

![image](https://user-images.githubusercontent.com/44423/85689825-e3d11180-b6ca-11ea-94d7-be09613a0c6b.png)

Other info in case it's useful:
- `npx framer-cli build ./cosmos.framerfx` outputs "📦 Package successfully built."
-  `npx framer-cli version ./cosmos.framerfx` outputs "Cannot retrieve the latest version."


Thanks again!

**Comment by addisonschultz** [comment]
Hmm this is an odd error. Can you share your `package.json` as well? It might be better to continue this conversation elsewhere, you can reach out to support@framer.com and mention my name, and we can pick it up from there!

**Comment by addisonschultz** [comment]
Closing this ticket, as this is an issue with the Framer CLI, not the starter kit.
