### ISSUE TITLE
Folder build stays empty after successful build

### ISSUE THREAD

**Issue by jakubsgit** [framer/framer-bridge-starter-kit#30]
When the command build with framer-cli is fired and go through successfully the folder in framerfx stays empty.

![framer](https://user-images.githubusercontent.com/50321236/102336634-b8e8bb80-3f91-11eb-80e1-2a13187c579f.png)

**Comment by addisonschultz** [comment]
Can you run me through the steps you took? I cannot reproduce, it seems to be working! 

A few things to check: 

- Make sure you refresh after running the command, it could be your IDE doesn't update or show the built folder even though it was built on your machine.
- Make sure you're running the command inside the directory of this project. 

Additional screenshots / recordings of what's not working are additionally helpful!

**Comment by jakubsgit** [comment]
Firstly I've forked starter-kit repo to my local machine
Then after all dependencies were installed with yarn command I successfully authorized with the email that I provided before in Framer browser client. 
I've got an authorization token that was useful during getting the project built. Then I've published the new project to the public store that was empty once I inserted it in the Framer. 
![felixframer](https://user-images.githubusercontent.com/50321236/102338342-05cd9180-3f94-11eb-851d-e350eac45959.png)

**Comment by addisonschultz** [comment]
I found the issue - I'll update this repo

This project needs to be opened in Framer X51 (old Framer) before the project will be built, and then possible to be opened in Current Framer Desktop 

You can update the file located at `design/document.json`, at the very bottom. Update the `version` to `75`, and make sure you open the file in the latest Framer Desktop (https://framer.com/desktop) 

From here, you should see the components in the project and get everything working. I'll update this repository to reflect the changes, and close the ticket in the meantime! Thanks for pointing this out.

**Comment by jakubsgit** [comment]
If it is possible to make it without Framer Desktop that is only available for macOS?
