### ISSUE TITLE
Bridge Recipes / Examples

### ISSUE THREAD

**Issue by davo** [framer/framer-bridge-starter-kit#8]
**Idea:**
Provide better support to use Framer Bridge with other types of design systems implementations/configurations. 

**Description:**
Design system implementations comes in all sorts of shapes and colors these days, with a myriad of css/sass and css-in-js configurations, type settings, folder structures and packager configurations.

Do you think it would be valuable to made a community effort to create examples with different integration strategies for Framer Bridge?

**References:**
Next.js bring an amazing DX by showcasing many different ways to implement the framework.
Also, Expo, the React Native tooling & deployment service have a vast collection of examples.  
- [Next.js Examples](https://github.com/zeit/next.js/tree/canary/examples/)
- [Expo Examples](https://github.com/expo/examples)
- [Theme UI Examples](https://github.com/system-ui/theme-ui/tree/master/examples)

**Comment by camacho** [comment]
This sounds like a great idea! Do you have an example in mind @davo?

**Comment by davo** [comment]
Patrick, I will probably invest time on a SCSS/SASS based project, which is, still, a very common scenario.

I wonder if @LucasRitter had any ideas on this, since he made one of the first design system implementation (with [AtlasKit for Framer X](https://github.com/atlassian/atlaskit-framerx)).

**Comment by glomotion** [comment]
+1

I did find an [older tutorial](https://blog.prototypr.io/bringing-design-system-components-from-production-into-framer-x-786e89be2250) which walks you through creating a minimal webpack build system which transpiles down the production components into generic ES5 and copies them into the framerx project zips - although I wasn't able to get it all working with the new framerx. Honestly, It feels like this should be less complicated now that we can have "folder projects". 

I'd be super interested to see how things would work when trying to use sass/scss/less syntax combined with css-modules (where css-modules is of course, the really important part).

**Comment by magbicaleman** [comment]
I'm not sure if this is what you're looking for but it seems like it.

@lintonye has some great examples, mainly in the `production-bundle` directory
- https://github.com/lintonye/framerx-design-system-demos

**Comment by addisonschultz** [comment]
This is great feedback from everyone. We're always aiming to make the integration of Design Systems better and better in Framer X, and recently have been making some great progress towards this. 

I wrote this article a little bit ago to help understand new ways Design Systems can be consumed in Framer X, and gave some tips / new starting points for those wishing to try a different workflow.

https://medium.com/@addisonschultz/design-systems-in-framer-x-e013c065457c

Keep an eye on some of these repositories, as we have many plans to continue improving and extending in these areas!

**Comment by davo** [comment]
Hey @addisonschultz sorry for the candor... but I'm a bit bummed by this, tbh.

I guess I was expecting more, not only from @framer but also from the power users on the community.

Can we give try to spin this again, somehow, more like a path for contribution rather than just providing feedback.

Maybe by pulling resource into creating a [contribution guide](https://github.com/facebook/react/blob/master/CONTRIBUTING.md).

Again, Bridge as a strategy for code reuse it's great on paper, but we do need more support to take it off the ground.
