### ISSUE TITLE
Framer Private Store Publishing Example

### ISSUE THREAD

**Issue by rfinni** [framer/framer-bridge-starter-kit#9]
This is not an issue but a question around the publishing process to a Framer private team store. The example shown in this starter kit has the .framerfx file in the same repo as the components that are built to the Framer file. Is it possible to have the .framerfx file either in a completely separate repo than the components, or not in a repo at all?

The part in question within the Github action is: 

```
action "Build" {
   uses = "framer/bridge@master"
   args = ["build", <your-project-path.framerfx>]
 }
```

In the scenario described above, what would replace ```<your-project-path.framerfx>```?

Thanks!

**Comment by camacho** [comment]
Hi @rfinni - the GitHub action can only apply to files in the repository meaning the `.framerfx` file would need to be collocated for the action to be usable. The path to `<your-project-path.framerfx>` is relative to the root of the repository.

However, just like with any other automation system, it is possible to roll a custom solution along with the [Framer CLI](https://www.npmjs.com/package/framer-cli) to build a custom publish workflow.

**Comment by rfinni** [comment]
@camacho thanks for your reply. It seems I will need to look more into the CLI tool for a custom solution.

**Comment by addisonschultz** [comment]
@rfinni do you have an ideal setup you'd like to have? We've been testing out a lot of different workflows with Framer Bridge recently, and happy to show some examples if there is a setup you're  interested in having.

**Comment by addisonschultz** [comment]
You can also read [this](https://medium.com/@addisonschultz/design-systems-in-framer-x-e013c065457c) to get some other ideas on how to consume/update a design system using framer-bridge
